name: workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        run: mvn install

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: AutoReferee.jar
          path: target/AutoReferee.jar
